name: Build a Docker image
description: Builds a Docker image based on ./docker/Dockerfile, and using a tag passed as a parameter

inputs:
  tag:
    description: Tag for the built Docker image
    required: true

runs:
  using: "composite"
  steps:
    - name: Build the image itself
      shell: bash
      run: docker build -t ${{ inputs.tag }} -f docker/Dockerfile .
