name: Release on Docker Hub upon pushing a tag

on:
  push:
    tags:
      - '*'

jobs:
  preparations:
    name: Preparations
    uses: ./.github/workflows/push.yml

  docker-publish:
    name: Publish Docker image as tag
    needs: [ "preparations" ]
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image from artifacts
        uses: actions/download-artifact@v3
        with:
          name: price-feeds-poller.tar
          path: /tmp
      - name: Load Docker image
        run: docker load --input /tmp/price-feeds-poller.tar
      - name: Tag image
        run: docker tag witnet/price-feeds-poller:latest witnet/price-feeds-poller:${{github.ref_name}}
      - name: Log into Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image to Docker Hub
        run: |
          docker push witnet/price-feeds-poller:${{github.ref_name}}
          docker push witnet/price-feeds-poller:latest

